greeting: Hello

endpoints:
  health:
    sensitive: false


    
spring:
  application:
    name: springbox-catalog
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
  jpa:
    database: MYSQL